/* 
 * KIE Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 7.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Victor.CUI.RHDM.KIE.Api;
using Victor.CUI.RHDM.KIE.Model;
using Victor.CUI.RHDM.KIE.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Victor.Tests.RHDM
{
    /// <summary>
    ///  Class for testing SolverInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SolverInstanceTests
    {
        // TODO uncomment below to declare an instance variable for SolverInstance
        //private SolverInstance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SolverInstance
            //instance = new SolverInstance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SolverInstance
        /// </summary>
        [Test]
        public void SolverInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SolverInstance
            //Assert.IsInstanceOfType<SolverInstance> (instance, "variable 'instance' is a SolverInstance");
        }


        /// <summary>
        /// Test the property 'ContainerId'
        /// </summary>
        [Test]
        public void ContainerIdTest()
        {
            // TODO unit test for the property 'ContainerId'
        }
        /// <summary>
        /// Test the property 'SolverId'
        /// </summary>
        [Test]
        public void SolverIdTest()
        {
            // TODO unit test for the property 'SolverId'
        }
        /// <summary>
        /// Test the property 'SolverConfigFile'
        /// </summary>
        [Test]
        public void SolverConfigFileTest()
        {
            // TODO unit test for the property 'SolverConfigFile'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'BestSolution'
        /// </summary>
        [Test]
        public void BestSolutionTest()
        {
            // TODO unit test for the property 'BestSolution'
        }

    }

}
