// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GitSourceRevision is the commit information from a git source for a
    /// build
    /// </summary>
    public partial class Comgithubopenshiftapibuildv1GitSourceRevision
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapibuildv1GitSourceRevision class.
        /// </summary>
        public Comgithubopenshiftapibuildv1GitSourceRevision() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapibuildv1GitSourceRevision class.
        /// </summary>
        public Comgithubopenshiftapibuildv1GitSourceRevision(Comgithubopenshiftapibuildv1SourceControlUser author = default(Comgithubopenshiftapibuildv1SourceControlUser), string commit = default(string), Comgithubopenshiftapibuildv1SourceControlUser committer = default(Comgithubopenshiftapibuildv1SourceControlUser), string message = default(string))
        {
            Author = author;
            Commit = commit;
            Committer = committer;
            Message = message;
        }

        /// <summary>
        /// author is the author of a specific commit
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public Comgithubopenshiftapibuildv1SourceControlUser Author { get; set; }

        /// <summary>
        /// commit is the commit hash identifying a specific commit
        /// </summary>
        [JsonProperty(PropertyName = "commit")]
        public string Commit { get; set; }

        /// <summary>
        /// committer is the committer of a specific commit
        /// </summary>
        [JsonProperty(PropertyName = "committer")]
        public Comgithubopenshiftapibuildv1SourceControlUser Committer { get; set; }

        /// <summary>
        /// message is the description of a specific commit
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
