// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// RepositoryImportStatus describes the result of an image repository
    /// import
    /// </summary>
    public partial class Comgithubopenshiftapiimagev1RepositoryImportStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiimagev1RepositoryImportStatus class.
        /// </summary>
        public Comgithubopenshiftapiimagev1RepositoryImportStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiimagev1RepositoryImportStatus class.
        /// </summary>
        public Comgithubopenshiftapiimagev1RepositoryImportStatus(IList<string> additionalTags = default(IList<string>), IList<Comgithubopenshiftapiimagev1ImageImportStatus> images = default(IList<Comgithubopenshiftapiimagev1ImageImportStatus>), Iok8sapimachinerypkgapismetav1Status status = default(Iok8sapimachinerypkgapismetav1Status))
        {
            AdditionalTags = additionalTags;
            Images = images;
            Status = status;
        }

        /// <summary>
        /// AdditionalTags are tags that exist in the repository but were not
        /// imported because a maximum limit of automatic imports was applied.
        /// </summary>
        [JsonProperty(PropertyName = "additionalTags")]
        public IList<string> AdditionalTags { get; set; }

        /// <summary>
        /// Images is a list of images successfully retrieved by the import of
        /// the repository.
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<Comgithubopenshiftapiimagev1ImageImportStatus> Images { get; set; }

        /// <summary>
        /// Status reflects whether any failure occurred during import
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public Iok8sapimachinerypkgapismetav1Status Status { get; set; }

    }
}
