// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// EgressNetworkPolicyPeer specifies a target to apply egress network
    /// policy to
    /// </summary>
    public partial class Comgithubopenshiftapinetworkv1EgressNetworkPolicyPeer
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapinetworkv1EgressNetworkPolicyPeer class.
        /// </summary>
        public Comgithubopenshiftapinetworkv1EgressNetworkPolicyPeer() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapinetworkv1EgressNetworkPolicyPeer class.
        /// </summary>
        public Comgithubopenshiftapinetworkv1EgressNetworkPolicyPeer(string cidrSelector = default(string), string dnsName = default(string))
        {
            CidrSelector = cidrSelector;
            DnsName = dnsName;
        }

        /// <summary>
        /// cidrSelector is the CIDR range to allow/deny traffic to. If this
        /// is set, dnsName must be unset
        /// </summary>
        [JsonProperty(PropertyName = "cidrSelector")]
        public string CidrSelector { get; set; }

        /// <summary>
        /// dnsName is the domain name to allow/deny traffic to. If this is
        /// set, cidrSelector must be unset
        /// </summary>
        [JsonProperty(PropertyName = "dnsName")]
        public string DnsName { get; set; }

    }
}
