// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// DeploymentCauseImageTrigger represents details about the cause of a
    /// deployment originating from an image change trigger
    /// </summary>
    public partial class Comgithubopenshiftapiappsv1DeploymentCauseImageTrigger
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiappsv1DeploymentCauseImageTrigger class.
        /// </summary>
        public Comgithubopenshiftapiappsv1DeploymentCauseImageTrigger() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiappsv1DeploymentCauseImageTrigger class.
        /// </summary>
        public Comgithubopenshiftapiappsv1DeploymentCauseImageTrigger(Iok8sapicorev1ObjectReference fromProperty)
        {
            FromProperty = fromProperty;
        }

        /// <summary>
        /// From is a reference to the changed object which triggered a
        /// deployment. The field may have the kinds DockerImage,
        /// ImageStreamTag, or ImageStreamImage.
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public Iok8sapicorev1ObjectReference FromProperty { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (FromProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FromProperty");
            }
        }
    }
}
