// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// IDRange provides a min/max of an allowed range of IDs.
    /// </summary>
    public partial class Comgithubopenshiftapisecurityv1IDRange
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapisecurityv1IDRange class.
        /// </summary>
        public Comgithubopenshiftapisecurityv1IDRange() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapisecurityv1IDRange class.
        /// </summary>
        public Comgithubopenshiftapisecurityv1IDRange(long? max = default(long?), long? min = default(long?))
        {
            Max = max;
            Min = min;
        }

        /// <summary>
        /// Max is the end of the range, inclusive.
        /// </summary>
        [JsonProperty(PropertyName = "max")]
        public long? Max { get; set; }

        /// <summary>
        /// Min is the start of the range, inclusive.
        /// </summary>
        [JsonProperty(PropertyName = "min")]
        public long? Min { get; set; }

    }
}
