// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// RoutePort defines a port mapping from a router to an endpoint in the
    /// service endpoints.
    /// </summary>
    public partial class Comgithubopenshiftapiroutev1RoutePort
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiroutev1RoutePort class.
        /// </summary>
        public Comgithubopenshiftapiroutev1RoutePort() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapiroutev1RoutePort class.
        /// </summary>
        public Comgithubopenshiftapiroutev1RoutePort(string targetPort)
        {
            TargetPort = targetPort;
        }

        /// <summary>
        /// The target port on pods selected by the service this route points
        /// to. If this is a string, it will be looked up as a named port in
        /// the target endpoints port list. Required
        /// </summary>
        [JsonProperty(PropertyName = "targetPort")]
        public string TargetPort { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TargetPort == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TargetPort");
            }
        }
    }
}
