// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// TemplateInstanceObject references an object created by a
    /// TemplateInstance.
    /// </summary>
    public partial class Comgithubopenshiftapitemplatev1TemplateInstanceObject
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapitemplatev1TemplateInstanceObject class.
        /// </summary>
        public Comgithubopenshiftapitemplatev1TemplateInstanceObject() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftapitemplatev1TemplateInstanceObject class.
        /// </summary>
        public Comgithubopenshiftapitemplatev1TemplateInstanceObject(Iok8sapicorev1ObjectReference refProperty = default(Iok8sapicorev1ObjectReference))
        {
            RefProperty = refProperty;
        }

        /// <summary>
        /// ref is a reference to the created object.  When used under .spec,
        /// only name and namespace are used; these can contain references to
        /// parameters which will be substituted following the usual rules.
        /// </summary>
        [JsonProperty(PropertyName = "ref")]
        public Iok8sapicorev1ObjectReference RefProperty { get; set; }

    }
}
