// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Iok8sapicertificatesv1beta1CertificateSigningRequestStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicertificatesv1beta1CertificateSigningRequestStatus class.
        /// </summary>
        public Iok8sapicertificatesv1beta1CertificateSigningRequestStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicertificatesv1beta1CertificateSigningRequestStatus class.
        /// </summary>
        public Iok8sapicertificatesv1beta1CertificateSigningRequestStatus(byte[] certificate = default(byte[]), IList<Iok8sapicertificatesv1beta1CertificateSigningRequestCondition> conditions = default(IList<Iok8sapicertificatesv1beta1CertificateSigningRequestCondition>))
        {
            Certificate = certificate;
            Conditions = conditions;
        }

        /// <summary>
        /// If request was approved, the controller will place the issued
        /// certificate here.
        /// </summary>
        [JsonProperty(PropertyName = "certificate")]
        public byte[] Certificate { get; set; }

        /// <summary>
        /// Conditions applied to the request, such as approval or denial.
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<Iok8sapicertificatesv1beta1CertificateSigningRequestCondition> Conditions { get; set; }

    }
}
