// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// StatusCause provides more information about an api.Status failure,
    /// including cases when multiple errors are encountered.
    /// </summary>
    public partial class Iok8sapimachinerypkgapismetav1StatusCause
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1StatusCause class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1StatusCause() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1StatusCause class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1StatusCause(string field = default(string), string message = default(string), string reason = default(string))
        {
            Field = field;
            Message = message;
            Reason = reason;
        }

        /// <summary>
        /// The field of the resource that has caused this error, as named by
        /// its JSON serialization. May include dot and postfix notation for
        /// nested attributes. Arrays are zero-indexed.  Fields may appear
        /// more than once in an array of causes due to fields having
        /// multiple errors. Optional.
        /// 
        /// Examples:
        /// "name" - the field "name" on the current resource
        /// "items[0].name" - the field "name" on the first array entry in
        /// "items"
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// A human-readable description of the cause of the error.  This
        /// field may be presented as-is to a reader.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// A machine-readable description of the cause of the error. If this
        /// value is empty there is no information available.
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

    }
}
