// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// DaemonSetStatus represents the current status of a daemon set.
    /// </summary>
    public partial class Iok8sapiextensionsv1beta1DaemonSetStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1DaemonSetStatus class.
        /// </summary>
        public Iok8sapiextensionsv1beta1DaemonSetStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1DaemonSetStatus class.
        /// </summary>
        public Iok8sapiextensionsv1beta1DaemonSetStatus(int currentNumberScheduled, int desiredNumberScheduled, int numberMisscheduled, int numberReady, int? collisionCount = default(int?), IList<Iok8sapiextensionsv1beta1DaemonSetCondition> conditions = default(IList<Iok8sapiextensionsv1beta1DaemonSetCondition>), int? numberAvailable = default(int?), int? numberUnavailable = default(int?), long? observedGeneration = default(long?), int? updatedNumberScheduled = default(int?))
        {
            CollisionCount = collisionCount;
            Conditions = conditions;
            CurrentNumberScheduled = currentNumberScheduled;
            DesiredNumberScheduled = desiredNumberScheduled;
            NumberAvailable = numberAvailable;
            NumberMisscheduled = numberMisscheduled;
            NumberReady = numberReady;
            NumberUnavailable = numberUnavailable;
            ObservedGeneration = observedGeneration;
            UpdatedNumberScheduled = updatedNumberScheduled;
        }

        /// <summary>
        /// Count of hash collisions for the DaemonSet. The DaemonSet
        /// controller uses this field as a collision avoidance mechanism
        /// when it needs to create the name for the newest
        /// ControllerRevision.
        /// </summary>
        [JsonProperty(PropertyName = "collisionCount")]
        public int? CollisionCount { get; set; }

        /// <summary>
        /// Represents the latest available observations of a DaemonSet's
        /// current state.
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<Iok8sapiextensionsv1beta1DaemonSetCondition> Conditions { get; set; }

        /// <summary>
        /// The number of nodes that are running at least 1 daemon pod and are
        /// supposed to run the daemon pod. More info:
        /// https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
        /// </summary>
        [JsonProperty(PropertyName = "currentNumberScheduled")]
        public int CurrentNumberScheduled { get; set; }

        /// <summary>
        /// The total number of nodes that should be running the daemon pod
        /// (including nodes correctly running the daemon pod). More info:
        /// https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
        /// </summary>
        [JsonProperty(PropertyName = "desiredNumberScheduled")]
        public int DesiredNumberScheduled { get; set; }

        /// <summary>
        /// The number of nodes that should be running the daemon pod and have
        /// one or more of the daemon pod running and available (ready for at
        /// least spec.minReadySeconds)
        /// </summary>
        [JsonProperty(PropertyName = "numberAvailable")]
        public int? NumberAvailable { get; set; }

        /// <summary>
        /// The number of nodes that are running the daemon pod, but are not
        /// supposed to run the daemon pod. More info:
        /// https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
        /// </summary>
        [JsonProperty(PropertyName = "numberMisscheduled")]
        public int NumberMisscheduled { get; set; }

        /// <summary>
        /// The number of nodes that should be running the daemon pod and have
        /// one or more of the daemon pod running and ready.
        /// </summary>
        [JsonProperty(PropertyName = "numberReady")]
        public int NumberReady { get; set; }

        /// <summary>
        /// The number of nodes that should be running the daemon pod and have
        /// none of the daemon pod running and available (ready for at least
        /// spec.minReadySeconds)
        /// </summary>
        [JsonProperty(PropertyName = "numberUnavailable")]
        public int? NumberUnavailable { get; set; }

        /// <summary>
        /// The most recent generation observed by the daemon set controller.
        /// </summary>
        [JsonProperty(PropertyName = "observedGeneration")]
        public long? ObservedGeneration { get; set; }

        /// <summary>
        /// The total number of nodes that are running updated daemon pod
        /// </summary>
        [JsonProperty(PropertyName = "updatedNumberScheduled")]
        public int? UpdatedNumberScheduled { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Conditions != null)
            {
                foreach (var element in this.Conditions)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
