// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ServiceAccount binds together: * a name, understood by users, and
    /// perhaps by peripheral systems, for an identity * a principal that can
    /// be authenticated and authorized * a set of secrets
    /// </summary>
    public partial class Iok8sapicorev1ServiceAccount
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ServiceAccount
        /// class.
        /// </summary>
        public Iok8sapicorev1ServiceAccount() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ServiceAccount
        /// class.
        /// </summary>
        public Iok8sapicorev1ServiceAccount(string apiVersion = default(string), bool? automountServiceAccountToken = default(bool?), IList<Iok8sapicorev1LocalObjectReference> imagePullSecrets = default(IList<Iok8sapicorev1LocalObjectReference>), string kind = default(string), Iok8sapimachinerypkgapismetav1ObjectMeta metadata = default(Iok8sapimachinerypkgapismetav1ObjectMeta), IList<Iok8sapicorev1ObjectReference> secrets = default(IList<Iok8sapicorev1ObjectReference>))
        {
            ApiVersion = apiVersion;
            AutomountServiceAccountToken = automountServiceAccountToken;
            ImagePullSecrets = imagePullSecrets;
            Kind = kind;
            Metadata = metadata;
            Secrets = secrets;
        }

        /// <summary>
        /// APIVersion defines the versioned schema of this representation of
        /// an object. Servers should convert recognized schemas to the
        /// latest internal value, and may reject unrecognized values. More
        /// info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
        /// </summary>
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        /// <summary>
        /// AutomountServiceAccountToken indicates whether pods running as
        /// this service account should have an API token automatically
        /// mounted. Can be overridden at the pod level.
        /// </summary>
        [JsonProperty(PropertyName = "automountServiceAccountToken")]
        public bool? AutomountServiceAccountToken { get; set; }

        /// <summary>
        /// ImagePullSecrets is a list of references to secrets in the same
        /// namespace to use for pulling any images in pods that reference
        /// this ServiceAccount. ImagePullSecrets are distinct from Secrets
        /// because Secrets can be mounted in the pod, but ImagePullSecrets
        /// are only accessed by the kubelet. More info:
        /// https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
        /// </summary>
        [JsonProperty(PropertyName = "imagePullSecrets")]
        public IList<Iok8sapicorev1LocalObjectReference> ImagePullSecrets { get; set; }

        /// <summary>
        /// Kind is a string value representing the REST resource this object
        /// represents. Servers may infer this from the endpoint the client
        /// submits requests to. Cannot be updated. In CamelCase. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Standard object's metadata. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public Iok8sapimachinerypkgapismetav1ObjectMeta Metadata { get; set; }

        /// <summary>
        /// Secrets is the list of secrets allowed to be used by pods running
        /// using this ServiceAccount. More info:
        /// https://kubernetes.io/docs/concepts/configuration/secret
        /// </summary>
        [JsonProperty(PropertyName = "secrets")]
        public IList<Iok8sapicorev1ObjectReference> Secrets { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Metadata != null)
            {
                this.Metadata.Validate();
            }
        }
    }
}
