// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ResourceQuotaSpec defines the desired hard limits to enforce for Quota.
    /// </summary>
    public partial class Iok8sapicorev1ResourceQuotaSpec
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ResourceQuotaSpec
        /// class.
        /// </summary>
        public Iok8sapicorev1ResourceQuotaSpec() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ResourceQuotaSpec
        /// class.
        /// </summary>
        public Iok8sapicorev1ResourceQuotaSpec(IDictionary<string, string> hard = default(IDictionary<string, string>), IList<string> scopes = default(IList<string>))
        {
            Hard = hard;
            Scopes = scopes;
        }

        /// <summary>
        /// Hard is the set of desired hard limits for each named resource.
        /// More info:
        /// https://kubernetes.io/docs/concepts/policy/resource-quotas/
        /// </summary>
        [JsonProperty(PropertyName = "hard")]
        public IDictionary<string, string> Hard { get; set; }

        /// <summary>
        /// A collection of filters that must match each object tracked by a
        /// quota. If not specified, the quota matches all objects.
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

    }
}
