// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// SubjectAccessReview checks whether or not a user or group can perform
    /// an action.
    /// </summary>
    public partial class Iok8sapiauthorizationv1beta1SubjectAccessReview
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1beta1SubjectAccessReview class.
        /// </summary>
        public Iok8sapiauthorizationv1beta1SubjectAccessReview() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1beta1SubjectAccessReview class.
        /// </summary>
        public Iok8sapiauthorizationv1beta1SubjectAccessReview(Iok8sapiauthorizationv1beta1SubjectAccessReviewSpec spec, string apiVersion = default(string), string kind = default(string), Iok8sapimachinerypkgapismetav1ObjectMeta metadata = default(Iok8sapimachinerypkgapismetav1ObjectMeta), Iok8sapiauthorizationv1beta1SubjectAccessReviewStatus status = default(Iok8sapiauthorizationv1beta1SubjectAccessReviewStatus))
        {
            ApiVersion = apiVersion;
            Kind = kind;
            Metadata = metadata;
            Spec = spec;
            Status = status;
        }

        /// <summary>
        /// APIVersion defines the versioned schema of this representation of
        /// an object. Servers should convert recognized schemas to the
        /// latest internal value, and may reject unrecognized values. More
        /// info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
        /// </summary>
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        /// <summary>
        /// Kind is a string value representing the REST resource this object
        /// represents. Servers may infer this from the endpoint the client
        /// submits requests to. Cannot be updated. In CamelCase. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public Iok8sapimachinerypkgapismetav1ObjectMeta Metadata { get; set; }

        /// <summary>
        /// Spec holds information about the request being evaluated
        /// </summary>
        [JsonProperty(PropertyName = "spec")]
        public Iok8sapiauthorizationv1beta1SubjectAccessReviewSpec Spec { get; set; }

        /// <summary>
        /// Status is filled in by the server and indicates whether the
        /// request is allowed or not
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public Iok8sapiauthorizationv1beta1SubjectAccessReviewStatus Status { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Spec == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Spec");
            }
            if (this.Metadata != null)
            {
                this.Metadata.Validate();
            }
            if (this.Status != null)
            {
                this.Status.Validate();
            }
        }
    }
}
