// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ClientIPConfig represents the configurations of Client IP based
    /// session affinity.
    /// </summary>
    public partial class Iok8sapicorev1ClientIPConfig
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ClientIPConfig
        /// class.
        /// </summary>
        public Iok8sapicorev1ClientIPConfig() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ClientIPConfig
        /// class.
        /// </summary>
        public Iok8sapicorev1ClientIPConfig(int? timeoutSeconds = default(int?))
        {
            TimeoutSeconds = timeoutSeconds;
        }

        /// <summary>
        /// timeoutSeconds specifies the seconds of ClientIP type session
        /// sticky time. The value must be &gt;0 &amp;&amp; &lt;=86400(for 1
        /// day) if ServiceAffinity == "ClientIP". Default value is 10800(for
        /// 3 hours).
        /// </summary>
        [JsonProperty(PropertyName = "timeoutSeconds")]
        public int? TimeoutSeconds { get; set; }

    }
}
