// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ResourceRule is the list of actions the subject is allowed to perform
    /// on resources. The list ordering isn't significant, may contain
    /// duplicates, and possibly be incomplete.
    /// </summary>
    public partial class Iok8sapiauthorizationv1beta1ResourceRule
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1beta1ResourceRule class.
        /// </summary>
        public Iok8sapiauthorizationv1beta1ResourceRule() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiauthorizationv1beta1ResourceRule class.
        /// </summary>
        public Iok8sapiauthorizationv1beta1ResourceRule(IList<string> verbs, IList<string> apiGroups = default(IList<string>), IList<string> resourceNames = default(IList<string>), IList<string> resources = default(IList<string>))
        {
            ApiGroups = apiGroups;
            ResourceNames = resourceNames;
            Resources = resources;
            Verbs = verbs;
        }

        /// <summary>
        /// APIGroups is the name of the APIGroup that contains the resources.
        /// If multiple API groups are specified, any action requested
        /// against one of the enumerated resources in any API group will be
        /// allowed.  "*" means all.
        /// </summary>
        [JsonProperty(PropertyName = "apiGroups")]
        public IList<string> ApiGroups { get; set; }

        /// <summary>
        /// ResourceNames is an optional white list of names that the rule
        /// applies to.  An empty set means that everything is allowed.  "*"
        /// means all.
        /// </summary>
        [JsonProperty(PropertyName = "resourceNames")]
        public IList<string> ResourceNames { get; set; }

        /// <summary>
        /// Resources is a list of resources this rule applies to.  "*" means
        /// all in the specified apiGroups.
        /// "*/foo" represents the subresource 'foo' for all resources in the
        /// specified apiGroups.
        /// </summary>
        [JsonProperty(PropertyName = "resources")]
        public IList<string> Resources { get; set; }

        /// <summary>
        /// Verb is a list of kubernetes resource API verbs, like: get, list,
        /// watch, create, update, delete, proxy.  "*" means all.
        /// </summary>
        [JsonProperty(PropertyName = "verbs")]
        public IList<string> Verbs { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Verbs == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Verbs");
            }
        }
    }
}
