// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Local represents directly-attached storage with node affinity
    /// </summary>
    public partial class Iok8sapicorev1LocalVolumeSource
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1LocalVolumeSource
        /// class.
        /// </summary>
        public Iok8sapicorev1LocalVolumeSource() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1LocalVolumeSource
        /// class.
        /// </summary>
        public Iok8sapicorev1LocalVolumeSource(string path)
        {
            Path = path;
        }

        /// <summary>
        /// The full path to the volume on the node For alpha, this path must
        /// be a directory Once block as a source is supported, then this
        /// path can point to a block device
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Path == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Path");
            }
        }
    }
}
