// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Represents an empty directory for a pod. Empty directory volumes
    /// support ownership management and SELinux relabeling.
    /// </summary>
    public partial class Iok8sapicorev1EmptyDirVolumeSource
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1EmptyDirVolumeSource class.
        /// </summary>
        public Iok8sapicorev1EmptyDirVolumeSource() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1EmptyDirVolumeSource class.
        /// </summary>
        public Iok8sapicorev1EmptyDirVolumeSource(string medium = default(string), string sizeLimit = default(string))
        {
            Medium = medium;
            SizeLimit = sizeLimit;
        }

        /// <summary>
        /// What type of storage medium should back this directory. The
        /// default is "" which means to use the node's default medium. Must
        /// be an empty string (default) or Memory. More info:
        /// https://kubernetes.io/docs/concepts/storage/volumes#emptydir
        /// </summary>
        [JsonProperty(PropertyName = "medium")]
        public string Medium { get; set; }

        /// <summary>
        /// Total amount of local storage required for this EmptyDir volume.
        /// The size limit is also applicable for memory medium. The maximum
        /// usage on memory medium EmptyDir would be the minimum value
        /// between the SizeLimit specified here and the sum of memory limits
        /// of all containers in a pod. The default is nil which means that
        /// the limit is undefined. More info:
        /// http://kubernetes.io/docs/user-guide/volumes#emptydir
        /// </summary>
        [JsonProperty(PropertyName = "sizeLimit")]
        public string SizeLimit { get; set; }

    }
}
