// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ConfigMapEnvSource selects a ConfigMap to populate the environment
    /// variables with.
    /// 
    /// The contents of the target ConfigMap's Data field will represent the
    /// key-value pairs as environment variables.
    /// </summary>
    public partial class Iok8sapicorev1ConfigMapEnvSource
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ConfigMapEnvSource
        /// class.
        /// </summary>
        public Iok8sapicorev1ConfigMapEnvSource() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1ConfigMapEnvSource
        /// class.
        /// </summary>
        public Iok8sapicorev1ConfigMapEnvSource(string name = default(string), bool? optional = default(bool?))
        {
            Name = name;
            Optional = optional;
        }

        /// <summary>
        /// Name of the referent. More info:
        /// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Specify whether the ConfigMap must be defined
        /// </summary>
        [JsonProperty(PropertyName = "optional")]
        public bool? Optional { get; set; }

    }
}
