// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// AggregationRule describes how to locate ClusterRoles to aggregate into
    /// the ClusterRole
    /// </summary>
    public partial class Iok8sapirbacv1beta1AggregationRule
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapirbacv1beta1AggregationRule class.
        /// </summary>
        public Iok8sapirbacv1beta1AggregationRule() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapirbacv1beta1AggregationRule class.
        /// </summary>
        public Iok8sapirbacv1beta1AggregationRule(IList<Iok8sapimachinerypkgapismetav1LabelSelector> clusterRoleSelectors = default(IList<Iok8sapimachinerypkgapismetav1LabelSelector>))
        {
            ClusterRoleSelectors = clusterRoleSelectors;
        }

        /// <summary>
        /// ClusterRoleSelectors holds a list of selectors which will be used
        /// to find ClusterRoles and create the rules. If any of the
        /// selectors match, then the ClusterRole's permissions will be added
        /// </summary>
        [JsonProperty(PropertyName = "clusterRoleSelectors")]
        public IList<Iok8sapimachinerypkgapismetav1LabelSelector> ClusterRoleSelectors { get; set; }

    }
}
