// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ListMeta describes metadata that synthetic resources must have,
    /// including lists and various status objects. A resource may have only
    /// one of {ObjectMeta, ListMeta}.
    /// </summary>
    public partial class Iok8sapimachinerypkgapismetav1ListMeta
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1ListMeta class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1ListMeta() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1ListMeta class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1ListMeta(string continueProperty = default(string), string resourceVersion = default(string), string selfLink = default(string))
        {
            ContinueProperty = continueProperty;
            ResourceVersion = resourceVersion;
            SelfLink = selfLink;
        }

        /// <summary>
        /// continue may be set if the user set a limit on the number of items
        /// returned, and indicates that the server has more data available.
        /// The value is opaque and may be used to issue another request to
        /// the endpoint that served this list to retrieve the next set of
        /// available objects. Continuing a list may not be possible if the
        /// server configuration has changed or more than a few minutes have
        /// passed. The resourceVersion field returned when using this
        /// continue value will be identical to the value in the first
        /// response.
        /// </summary>
        [JsonProperty(PropertyName = "continue")]
        public string ContinueProperty { get; set; }

        /// <summary>
        /// String that identifies the server's internal version of this
        /// object that can be used by clients to determine when objects have
        /// changed. Value must be treated as opaque by clients and passed
        /// unmodified back to the server. Populated by the system.
        /// Read-only. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency
        /// </summary>
        [JsonProperty(PropertyName = "resourceVersion")]
        public string ResourceVersion { get; set; }

        /// <summary>
        /// selfLink is a URL representing this object. Populated by the
        /// system. Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "selfLink")]
        public string SelfLink { get; set; }

    }
}
