// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// EndpointAddress is a tuple that describes single IP address.
    /// </summary>
    public partial class Iok8sapicorev1EndpointAddress
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1EndpointAddress
        /// class.
        /// </summary>
        public Iok8sapicorev1EndpointAddress() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1EndpointAddress
        /// class.
        /// </summary>
        public Iok8sapicorev1EndpointAddress(string ip, string hostname = default(string), string nodeName = default(string), Iok8sapicorev1ObjectReference targetRef = default(Iok8sapicorev1ObjectReference))
        {
            Hostname = hostname;
            Ip = ip;
            NodeName = nodeName;
            TargetRef = targetRef;
        }

        /// <summary>
        /// The Hostname of this endpoint
        /// </summary>
        [JsonProperty(PropertyName = "hostname")]
        public string Hostname { get; set; }

        /// <summary>
        /// The IP of this endpoint. May not be loopback (127.0.0.0/8),
        /// link-local (169.254.0.0/16), or link-local multicast
        /// ((224.0.0.0/24). IPv6 is also accepted but not fully supported on
        /// all platforms. Also, certain kubernetes components, like
        /// kube-proxy, are not IPv6 ready.
        /// </summary>
        [JsonProperty(PropertyName = "ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Optional: Node hosting this endpoint. This can be used to
        /// determine endpoints local to a node.
        /// </summary>
        [JsonProperty(PropertyName = "nodeName")]
        public string NodeName { get; set; }

        /// <summary>
        /// Reference to object providing the endpoint.
        /// </summary>
        [JsonProperty(PropertyName = "targetRef")]
        public Iok8sapicorev1ObjectReference TargetRef { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Ip == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ip");
            }
        }
    }
}
