// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// HTTPHeader describes a custom header to be used in HTTP probes
    /// </summary>
    public partial class Iok8sapicorev1HTTPHeader
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1HTTPHeader class.
        /// </summary>
        public Iok8sapicorev1HTTPHeader() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1HTTPHeader class.
        /// </summary>
        public Iok8sapicorev1HTTPHeader(string name, string value)
        {
            Name = name;
            Value = value;
        }

        /// <summary>
        /// The header field name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// The header field value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Value == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Value");
            }
        }
    }
}
