// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// EventSource contains information for an event.
    /// </summary>
    public partial class Iok8sapicorev1EventSource
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1EventSource class.
        /// </summary>
        public Iok8sapicorev1EventSource() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1EventSource class.
        /// </summary>
        public Iok8sapicorev1EventSource(string component = default(string), string host = default(string))
        {
            Component = component;
            Host = host;
        }

        /// <summary>
        /// Component from which the event is generated.
        /// </summary>
        [JsonProperty(PropertyName = "component")]
        public string Component { get; set; }

        /// <summary>
        /// Node name on which the event is generated.
        /// </summary>
        [JsonProperty(PropertyName = "host")]
        public string Host { get; set; }

    }
}
