// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// defines the host volume conditions that will be enabled by a policy
    /// for pods to use. It requires the path prefix to be defined.
    /// </summary>
    public partial class Iok8sapiextensionsv1beta1AllowedHostPath
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1AllowedHostPath class.
        /// </summary>
        public Iok8sapiextensionsv1beta1AllowedHostPath() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1AllowedHostPath class.
        /// </summary>
        public Iok8sapiextensionsv1beta1AllowedHostPath(string pathPrefix = default(string))
        {
            PathPrefix = pathPrefix;
        }

        /// <summary>
        /// is the path prefix that the host volume must match. It does not
        /// support `*`. Trailing slashes are trimmed when validating the
        /// path prefix with a host path.
        /// 
        /// Examples: `/foo` would allow `/foo`, `/foo/` and `/foo/bar` `/foo`
        /// would not allow `/food` or `/etc/foo`
        /// </summary>
        [JsonProperty(PropertyName = "pathPrefix")]
        public string PathPrefix { get; set; }

    }
}
