// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// HostAlias holds the mapping between IP and hostnames that will be
    /// injected as an entry in the pod's hosts file.
    /// </summary>
    public partial class Iok8sapicorev1HostAlias
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1HostAlias class.
        /// </summary>
        public Iok8sapicorev1HostAlias() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1HostAlias class.
        /// </summary>
        public Iok8sapicorev1HostAlias(IList<string> hostnames = default(IList<string>), string ip = default(string))
        {
            Hostnames = hostnames;
            Ip = ip;
        }

        /// <summary>
        /// Hostnames for the above IP address.
        /// </summary>
        [JsonProperty(PropertyName = "hostnames")]
        public IList<string> Hostnames { get; set; }

        /// <summary>
        /// IP address of the host file entry.
        /// </summary>
        [JsonProperty(PropertyName = "ip")]
        public string Ip { get; set; }

    }
}
