// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// CronJobStatus represents the current state of a cron job.
    /// </summary>
    public partial class Iok8sapibatchv1beta1CronJobStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapibatchv1beta1CronJobStatus class.
        /// </summary>
        public Iok8sapibatchv1beta1CronJobStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapibatchv1beta1CronJobStatus class.
        /// </summary>
        public Iok8sapibatchv1beta1CronJobStatus(IList<Iok8sapicorev1ObjectReference> active = default(IList<Iok8sapicorev1ObjectReference>), DateTime? lastScheduleTime = default(DateTime?))
        {
            Active = active;
            LastScheduleTime = lastScheduleTime;
        }

        /// <summary>
        /// A list of pointers to currently running jobs.
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public IList<Iok8sapicorev1ObjectReference> Active { get; set; }

        /// <summary>
        /// Information when was the last time the job was successfully
        /// scheduled.
        /// </summary>
        [JsonProperty(PropertyName = "lastScheduleTime")]
        public DateTime? LastScheduleTime { get; set; }

    }
}
