// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// APIServiceStatus contains derived information about an API server
    /// </summary>
    public partial class Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceStatus
        /// class.
        /// </summary>
        public Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceStatus
        /// class.
        /// </summary>
        public Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceStatus(IList<Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceCondition> conditions = default(IList<Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceCondition>))
        {
            Conditions = conditions;
        }

        /// <summary>
        /// Current service state of apiService.
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<Iok8skubeAggregatorpkgapisapiregistrationv1beta1APIServiceCondition> Conditions { get; set; }

    }
}
