// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ResourceQuotaStatus defines the enforced hard limits and observed use.
    /// </summary>
    public partial class Iok8sapicorev1ResourceQuotaStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1ResourceQuotaStatus class.
        /// </summary>
        public Iok8sapicorev1ResourceQuotaStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1ResourceQuotaStatus class.
        /// </summary>
        public Iok8sapicorev1ResourceQuotaStatus(IDictionary<string, string> hard = default(IDictionary<string, string>), IDictionary<string, string> used = default(IDictionary<string, string>))
        {
            Hard = hard;
            Used = used;
        }

        /// <summary>
        /// Hard is the set of enforced hard limits for each named resource.
        /// More info:
        /// https://kubernetes.io/docs/concepts/policy/resource-quotas/
        /// </summary>
        [JsonProperty(PropertyName = "hard")]
        public IDictionary<string, string> Hard { get; set; }

        /// <summary>
        /// Used is the current observed total usage of the resource in the
        /// namespace.
        /// </summary>
        [JsonProperty(PropertyName = "used")]
        public IDictionary<string, string> Used { get; set; }

    }
}
