// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ID Range provides a min/max of an allowed range of IDs.
    /// </summary>
    public partial class Iok8sapiextensionsv1beta1IDRange
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapiextensionsv1beta1IDRange
        /// class.
        /// </summary>
        public Iok8sapiextensionsv1beta1IDRange() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapiextensionsv1beta1IDRange
        /// class.
        /// </summary>
        public Iok8sapiextensionsv1beta1IDRange(long max, long min)
        {
            Max = max;
            Min = min;
        }

        /// <summary>
        /// Max is the end of the range, inclusive.
        /// </summary>
        [JsonProperty(PropertyName = "max")]
        public long Max { get; set; }

        /// <summary>
        /// Min is the start of the range, inclusive.
        /// </summary>
        [JsonProperty(PropertyName = "min")]
        public long Min { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
