// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ScaleSpec describes the attributes of a scale subresource
    /// </summary>
    public partial class Iok8sapiappsv1beta1ScaleSpec
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapiappsv1beta1ScaleSpec
        /// class.
        /// </summary>
        public Iok8sapiappsv1beta1ScaleSpec() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapiappsv1beta1ScaleSpec
        /// class.
        /// </summary>
        public Iok8sapiappsv1beta1ScaleSpec(int? replicas = default(int?))
        {
            Replicas = replicas;
        }

        /// <summary>
        /// desired number of instances for the scaled object.
        /// </summary>
        [JsonProperty(PropertyName = "replicas")]
        public int? Replicas { get; set; }

    }
}
