// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// PersistentVolumeClaimCondition contails details about state of pvc
    /// </summary>
    public partial class Iok8sapicorev1PersistentVolumeClaimCondition
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1PersistentVolumeClaimCondition class.
        /// </summary>
        public Iok8sapicorev1PersistentVolumeClaimCondition() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapicorev1PersistentVolumeClaimCondition class.
        /// </summary>
        public Iok8sapicorev1PersistentVolumeClaimCondition(string status, string type, DateTime? lastProbeTime = default(DateTime?), DateTime? lastTransitionTime = default(DateTime?), string message = default(string), string reason = default(string))
        {
            LastProbeTime = lastProbeTime;
            LastTransitionTime = lastTransitionTime;
            Message = message;
            Reason = reason;
            Status = status;
            Type = type;
        }

        /// <summary>
        /// Last time we probed the condition.
        /// </summary>
        [JsonProperty(PropertyName = "lastProbeTime")]
        public DateTime? LastProbeTime { get; set; }

        /// <summary>
        /// Last time the condition transitioned from one status to another.
        /// </summary>
        [JsonProperty(PropertyName = "lastTransitionTime")]
        public DateTime? LastTransitionTime { get; set; }

        /// <summary>
        /// Human-readable message indicating details about last transition.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Unique, this should be a short, machine understandable string that
        /// gives the reason for condition's last transition. If it reports
        /// "ResizeStarted" that means the underlying persistent volume is
        /// being resized.
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Status == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Status");
            }
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
