// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Represents a Fibre Channel volume. Fibre Channel volumes can only be
    /// mounted as read/write once. Fibre Channel volumes support ownership
    /// management and SELinux relabeling.
    /// </summary>
    public partial class Iok8sapicorev1FCVolumeSource
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1FCVolumeSource
        /// class.
        /// </summary>
        public Iok8sapicorev1FCVolumeSource() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1FCVolumeSource
        /// class.
        /// </summary>
        public Iok8sapicorev1FCVolumeSource(string fsType = default(string), int? lun = default(int?), bool? readOnlyProperty = default(bool?), IList<string> targetWWNs = default(IList<string>), IList<string> wwids = default(IList<string>))
        {
            FsType = fsType;
            Lun = lun;
            ReadOnlyProperty = readOnlyProperty;
            TargetWWNs = targetWWNs;
            Wwids = wwids;
        }

        /// <summary>
        /// Filesystem type to mount. Must be a filesystem type supported by
        /// the host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly
        /// inferred to be "ext4" if unspecified.
        /// </summary>
        [JsonProperty(PropertyName = "fsType")]
        public string FsType { get; set; }

        /// <summary>
        /// Optional: FC target lun number
        /// </summary>
        [JsonProperty(PropertyName = "lun")]
        public int? Lun { get; set; }

        /// <summary>
        /// Optional: Defaults to false (read/write). ReadOnly here will force
        /// the ReadOnly setting in VolumeMounts.
        /// </summary>
        [JsonProperty(PropertyName = "readOnly")]
        public bool? ReadOnlyProperty { get; set; }

        /// <summary>
        /// Optional: FC target worldwide names (WWNs)
        /// </summary>
        [JsonProperty(PropertyName = "targetWWNs")]
        public IList<string> TargetWWNs { get; set; }

        /// <summary>
        /// Optional: FC volume world wide identifiers (wwids) Either wwids or
        /// combination of targetWWNs and lun must be set, but not both
        /// simultaneously.
        /// </summary>
        [JsonProperty(PropertyName = "wwids")]
        public IList<string> Wwids { get; set; }

    }
}
