// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Adapts a secret into a projected volume.
    /// 
    /// The contents of the target Secret's Data field will be presented in a
    /// projected volume as files using the keys in the Data field as the
    /// file names. Note that this is identical to a secret volume source
    /// without the default mode.
    /// </summary>
    public partial class Iok8sapicorev1SecretProjection
    {
        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1SecretProjection
        /// class.
        /// </summary>
        public Iok8sapicorev1SecretProjection() { }

        /// <summary>
        /// Initializes a new instance of the Iok8sapicorev1SecretProjection
        /// class.
        /// </summary>
        public Iok8sapicorev1SecretProjection(IList<Iok8sapicorev1KeyToPath> items = default(IList<Iok8sapicorev1KeyToPath>), string name = default(string), bool? optional = default(bool?))
        {
            Items = items;
            Name = name;
            Optional = optional;
        }

        /// <summary>
        /// If unspecified, each key-value pair in the Data field of the
        /// referenced Secret will be projected into the volume as a file
        /// whose name is the key and content is the value. If specified, the
        /// listed keys will be projected into the specified paths, and
        /// unlisted keys will not be present. If a key is specified which is
        /// not present in the Secret, the volume setup will error unless it
        /// is marked optional. Paths must be relative and may not contain
        /// the '..' path or start with '..'.
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Iok8sapicorev1KeyToPath> Items { get; set; }

        /// <summary>
        /// Name of the referent. More info:
        /// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Specify whether the Secret or its key must be defined
        /// </summary>
        [JsonProperty(PropertyName = "optional")]
        public bool? Optional { get; set; }

    }
}
