// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Victor.CUI.Vish.OpenShift.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// AllowedFlexVolume represents a single Flexvolume that is allowed to be
    /// used.
    /// </summary>
    public partial class Iok8sapiextensionsv1beta1AllowedFlexVolume
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1AllowedFlexVolume class.
        /// </summary>
        public Iok8sapiextensionsv1beta1AllowedFlexVolume() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapiextensionsv1beta1AllowedFlexVolume class.
        /// </summary>
        public Iok8sapiextensionsv1beta1AllowedFlexVolume(string driver)
        {
            Driver = driver;
        }

        /// <summary>
        /// Driver is the name of the Flexvolume driver.
        /// </summary>
        [JsonProperty(PropertyName = "driver")]
        public string Driver { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Driver == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Driver");
            }
        }
    }
}
